### ISSUE TITLE
Sharing audio

### ISSUE THREAD

**Issue by egkoppel** [EZ-Code-Developer/sound-recorder#5]
Just showed it to my dad and he wants to be able to share the audio, without external applications like Total Commander

**Comment by ZeevoX** [comment]
YES BUT LETD FIX THE BUGS BEFORE CREATING NEW ONES.

**Comment by egkoppel** [comment]
Don't shout

**Comment by ZeevoX** [comment]
Just please... Don't ... Yet. We need to fix the bugs first. Otherwise we
end up with an application which we don't even understand how to fix and
where to start in the bug fixing process. Remember what happened with 1509
Online on github? People kept requesting features and we couldn't keep up
with bug fixing , so we had a lot of " wontfix" issues.

**Comment by egkoppel** [comment]
Ok
